###
POST http://localhost:4000/api/user HTTP/1.1
Content-Type: application/json

{
    "name": "Sebas",
    "lastName": "Chaves",
    "email": "sebasch@estudiantec.cr",
    "password": "1234",
    "status": "Active"}

### 
PUT http://localhost:4000/api/user/axelchaves.r@estudiantec.cr HTTP/1.1
Content-Type: application/json

{
    "name": "Pablo",
    "lastName": "Hidalgo",
    "email": "pablohidalgo@estudiantec.cr",
    "password": "1234",
    "status": "Active"
}


###
GET http://localhost:4000/